language: c

# use containers
sudo: false

addons:
  apt:
    sources:
    - r-packages-precise
    packages:
    - r-base-dev
    - r-recommended
    - pandoc
    - default-jdk
    - default-jre

# cache local R libraries directory:
cache:
  directories:
    - ~/Rlib

# install the package and dependencies:
install:
  - mkdir -p ~/Rlib
  - echo 'R_LIBS=~/Rlib' > .Renviron
  - echo 'options(repos = "http://cran.rstudio.com")' > .Rprofile
  - mkdir -p ~/.R
  - Rscript -e 'if (!require("devtools")) install.packages("devtools")'
  - Rscript -e 'if (!require("drat")) install.packages("drat")'
  - echo 'drat::addRepo("OHDSI")' >> .Rprofile
  - echo 'drat::addRepo("cloudyr")' >> .Rprofile  
  - Rscript -e 'if (!require("CohortMethod")) install.packages("CohortMethod", dependencies = TRUE)'
  - Rscript -e 'if (!require("OhdsiSharing")) install.packages("OhdsiSharing", dependencies = TRUE)'
  - Rscript -e 'if (!require("OhdsiRTools")) install.packages("OhdsiRTools", dependencies = TRUE)'      
  - Rscript -e 'if (!require("mailR")) install.packages("mailR", dependencies = TRUE)'
  - Rscript -e 'if (!require("ReporteRs")) install.packages("ReporteRs", dependencies = TRUE)'  
  - Rscript -e 'update.packages(ask = FALSE, instlib = "~/Rlib")'

before_script:
  - export PKG_NAME_KA=$(Rscript -e 'cat(paste0(devtools::as.package("./KeppraAngioedema")$package))')
  - export PKG_TARBALL_KA=$(Rscript -e 'pkg <- devtools::as.package("./KeppraAngioedema"); cat(paste0(pkg$package,"_",pkg$version,".tar.gz"))')
  - export PKG_NAME_AR=$(Rscript -e 'cat(paste0(devtools::as.package("./AlendronateVsRaloxifene")$package))')
  - export PKG_TARBALL_AR=$(Rscript -e 'pkg <- devtools::as.package("./AlendronateVsRaloxifene"); cat(paste0(pkg$package,"_",pkg$version,".tar.gz"))')
  

# Build and check NoacStudy package
script:
  - R CMD build KeppraAngioedema --no-build-vignettes --no-manual
  - _R_CHECK_CRAN_INCOMING_=FALSE R CMD check "${PKG_TARBALL_KA}" --no-build-vignettes --no-manual
  - cat ${PKG_NAME_KA}.Rcheck/00install.out # Print out install / compile log
  - R CMD build AlendronateVsRaloxifene --no-build-vignettes --no-manual
  - _R_CHECK_CRAN_INCOMING_=FALSE R CMD check "${PKG_TARBALL_AR}" --no-build-vignettes --no-manual
  - cat ${PKG_NAME_AR}.Rcheck/00install.out # Print out install / compile log  

notifications:
  recipients:
    - msuchard@gmail.com
    - schuemie@ohdsi.org
  email:
    on_success: change
    on_failure: change

after_success:
  # Deploy to drat repo
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh

env:
  global:
  - secure: ZzKAG80CmhulFZniuqpsR7uzxZltY1JkI7MZvluf/78KYAAYAZxeojElv6MVlHBGE7pCv00Y3Sd9LUKcv68i9fiCGGG3BsNqA6+4aXZd+Z+tscvmhza/86IEHet55rH4im1nhrEtD6K7FSrMzgyzJtMhilhG9DfVo/kBDpJjREk=
